// <auto-generated />
using CustomerManagement.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomerManagement.DataAccess.Migrations
{
    [DbContext(typeof(CustomerManagementContext))]
    [Migration("20221206180757_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomerManagement.Model.Models.Customers", b =>
                {
                    b.Property<int>("customerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CustomerId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("customerId"));

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character variyng")
                        .HasColumnName("City");

                    b.Property<string>("customerCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying")
                        .HasColumnName("CustomerCode");

                    b.Property<string>("customerTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying")
                        .HasColumnName("CustomerTitle");

                    b.Property<string>("district")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying")
                        .HasColumnName("District");

                    b.Property<int>("salesAmount")
                        .HasColumnType("integer")
                        .HasColumnName("SalesAmount");

                    b.HasKey("customerId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("CustomerManagement.Model.Models.Users", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userId"));

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying")
                        .HasColumnName("UserName");

                    b.Property<string>("userPassword")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying")
                        .HasColumnName("UserPassword");

                    b.HasKey("userId");

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
